---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstanceClass
metadata:
  name: standard-mysql
  annotations:
    resourceclass.crossplane.io/is-default-class: "true"
specTemplate:
  forProvider:
    dbInstanceClass: db.t2.small
    masterUsername: cool_user
    vpcSecurityGroupIDRefs:
      - name: sample-rds-sg
    dbSubnetGroupNameRef:
      name: sample-dbsubnetgroup
    allocatedStorage: 20
    engine: mysql
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretsToNamespace: crossplane-system
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
